import 'package:flutter/material.dart';

import 'models.dart';

const campusLocations = <CampusLocation>[
  CampusLocation(
    id: 1,
    name: 'Main Entrance',
    category: 'Entrance',
    block: 'Block C',
    floor: 'Ground floor',
    x: .72,
    y: .76,
    icon: Icons.login,
    aliases: ['entrance c', 'main door'],
  ),
  CampusLocation(
    id: 2,
    name: 'Library',
    category: 'Study',
    block: 'Block B',
    floor: '1st floor',
    x: .49,
    y: .88,
    icon: Icons.local_library_outlined,
    hours: '08:00–22:00',
    aliases: ['books', 'reading room'],
  ),
  CampusLocation(
    id: 3,
    name: 'Food Court',
    category: 'Food',
    block: 'Block F',
    floor: '1st floor',
    x: .74,
    y: .33,
    icon: Icons.restaurant_outlined,
    hours: '08:00–20:00',
    aliases: ['cafeteria', 'canteen', 'eat', 'coffee'],
  ),
  CampusLocation(
    id: 4,
    name: 'Room 317',
    category: 'Classroom',
    block: 'Block F',
    floor: '3rd floor',
    x: .43,
    y: .38,
    icon: Icons.meeting_room_outlined,
    aliases: ['317', 'f317'],
  ),
  CampusLocation(
    id: 5,
    name: 'Student Service Centre',
    category: 'Office',
    block: 'Block D',
    floor: '1st floor',
    x: .51,
    y: .61,
    icon: Icons.support_agent,
    hours: '09:00–18:00',
    aliases: ['ssc', 'student office'],
  ),
  CampusLocation(
    id: 6,
    name: 'Medical Point',
    category: 'Health',
    block: 'Block H',
    floor: '1st floor',
    x: .44,
    y: .18,
    icon: Icons.medical_services_outlined,
    aliases: ['doctor', 'clinic', 'first aid'],
  ),
  CampusLocation(
    id: 7,
    name: 'Printer — Engineering',
    category: 'Printer',
    block: 'Block F',
    floor: '2nd floor',
    x: .31,
    y: .34,
    icon: Icons.print_outlined,
    aliases: ['copy', 'printing'],
  ),
  CampusLocation(
    id: 8,
    name: 'Accessible Restroom',
    category: 'Restroom',
    block: 'Block E',
    floor: '1st floor',
    x: .48,
    y: .47,
    icon: Icons.accessible,
    aliases: ['toilet', 'wc'],
  ),
  CampusLocation(
    id: 9,
    name: 'ATM',
    category: 'Finance',
    block: 'Block G',
    floor: '1st floor',
    x: .26,
    y: .23,
    icon: Icons.account_balance_outlined,
    aliases: ['cash', 'bank'],
  ),
  CampusLocation(
    id: 10,
    name: 'Parking Entrance',
    category: 'Parking',
    block: 'Block H',
    floor: 'Outside',
    x: .80,
    y: .15,
    icon: Icons.local_parking,
    aliases: ['car park', 'park'],
  ),
  CampusLocation(
    id: 11,
    name: 'Teacher Office 215',
    category: 'Office',
    block: 'Block D',
    floor: '2nd floor',
    x: .39,
    y: .57,
    icon: Icons.badge_outlined,
    aliases: ['office hours', 'teacher'],
  ),
  CampusLocation(
    id: 12,
    name: 'Wi-Fi Lounge',
    category: 'Service',
    block: 'Block C',
    floor: '1st floor',
    x: .62,
    y: .78,
    icon: Icons.wifi,
    aliases: ['internet', 'lounge'],
  ),
];

const announcements = <CampusAnnouncement>[
  CampusAnnouncement(
    'Library extended hours',
    'Open until 22:00 during assessment week.',
    'Today',
    2,
  ),
  CampusAnnouncement(
    'Career fair',
    'Meet employers in the main atrium.',
    'Friday · 11:00',
    1,
  ),
  CampusAnnouncement(
    'Block F printer maintenance',
    'Use the printer in Block D until 14:00.',
    'Today · 09:30',
    7,
  ),
];

const routeSteps = <RouteStep>[
  RouteStep('Enter through the main Block C entrance', 1),
  RouteStep('Continue straight through the central atrium', 2),
  RouteStep('Pass Block E and follow signs toward Block F', 2),
  RouteStep('Take the elevator to the 3rd floor', 1),
  RouteStep('Room 317 is on your left', 0),
];
